import Head from 'next/head';
import { BiUserPlus } from "react-icons/bi";
import Table from '@/components/Tables/Table';
import style from './index.module.css'

function HomePage() {
  return (
    <section>
      <Head>
        <title>CRUD</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon" href="/favicon.ico"></link>
      </Head>

      <main className={style.main}>
        <h1 className={style.title}>Home Page</h1>
        <div className={style.container}>
          <div className={style.container_left}>
            <button className={style.button}>
              Add Employee
              <span className={style.icon}>
                <BiUserPlus size={23} />
              </span>
            </button>
          </div>
        </div>

        <div className={style.table}>
          <Table />
        </div>

      </main>
    </section>
  );
}

export default HomePage;
